### ISSUE TITLE
Unable to get gerrit to start up with cdelivery-core

### ISSUE THREAD

**Issue by garethjevans** [fabric8io/fabric8-installer#11]
Hi,

I'm using the vagrant installer, openshift-latest profile, and i've installed the "cdelivery-core" toolset. But I'm unable to get the gerrit image to start.  It appears to be constantly restarting.

From the logs

```[vagrant@vagrant ~]$ docker logs 4e4c3e711c16

> > .gerrit-configured doesn't exist. We will start gerrit to generate it
> > Exception in thread "main" java.io.IOException: Is a directory
> >     at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
> >     at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
> >     at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
> >     at sun.nio.ch.IOUtil.read(IOUtil.java:197)
> >     at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:149)
> >     at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
> >     at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
> >     at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
> >     at java.nio.file.Files.read(Files.java:2934)
> >     at java.nio.file.Files.readAllBytes(Files.java:2987)
> >     at com.googlesource.gerrit.plugins.AddUser.createSshKey(AddUser.java:335)
> >     at com.googlesource.gerrit.plugins.AddUser.readSshKey(AddUser.java:324)
> >     at com.googlesource.gerrit.plugins.AddUser.update(AddUser.java:248)
> >     at com.googlesource.gerrit.plugins.AddUser.postRun(AddUser.java:117)
> >     at com.google.gerrit.pgm.init.InitPlugins.postInitPlugins(InitPlugins.java:166)
> >     at com.google.gerrit.pgm.init.InitPlugins.postRun(InitPlugins.java:99)
> > 
> > ```
> > ```

When I try to start the image manually, e.g. docker run fabric8/gerrit it works.

Any pointers?

**Comment by christian-posta** [comment]
yah by default, we use some ssh keys to automatically create the gerrit Admin user.
It's on my todo list (or @cmoulliard ?) to get rid of the manual steps you need to talk to prep the host with the ssh keys and just use kube secrets. 

to manually prep the host (vagrant image) use this script locally:

https://github.com/fabric8io/docker-gerrit/blob/master/scripts/copy-keys-vagrant.sh

and the keys come from this project:

https://github.com/fabric8io/docker-gerrit/tree/master/ssh-keys

HTH... will let you know when we've eliminated these crufty manual steps

**Comment by garethjevans** [comment]
Thanks, will give that a go now

**Comment by garethjevans** [comment]
Perfect - that seems to be starting now - looks like you need to copy the keys before you try and start the image, otherwise it creates directories called id_rsa.pub and the copy fails.

Thanks for your help.

Gareth

**Comment by garethjevans** [comment]
This gets a lot further, but fails with an SQL error.  Could I now have too many keys?

```>> .gerrit-configured doesn't exist. We will start gerrit to generate it
Exception in thread "main" com.google.gwtorm.server.OrmDuplicateKeyException: account_ssh_keys
    at com.google.gwtorm.schema.sql.DialectH2.convertError(DialectH2.java:42)
    at com.google.gwtorm.jdbc.JdbcAccess.convertError(JdbcAccess.java:459)
    at com.google.gwtorm.jdbc.JdbcAccess.insert(JdbcAccess.java:170)
    at com.googlesource.gerrit.plugins.AddUser.update(AddUser.java:251)
    at com.googlesource.gerrit.plugins.AddUser.postRun(AddUser.java:117)
    at com.google.gerrit.pgm.init.InitPlugins.postInitPlugins(InitPlugins.java:166)
    at com.google.gerrit.pgm.init.InitPlugins.postRun(InitPlugins.java:99)
    at com.google.gerrit.pgm.init.SitePathInitializer.postRun(SitePathInitializer.java:129)
    at com.google.gerrit.pgm.init.BaseInit.run(BaseInit.java:122)
    at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:64)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:166)
    at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:93)
    at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:50)
    at Main.main(Main.java:25)
Caused by: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PRIMARY_KEY_E ON PUBLIC.ACCOUNT_SSH_KEYS(ACCOUNT_ID, SEQ) VALUES ( /\* key:4 _/ null, null, 1000000, 0)"; SQL statement:
INSERT INTO account_ssh_keys(ssh_public_key,valid,account_id,seq)VALUES(?,?,?,?) [23505-174]
    at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1167)
    at com.google.gwtorm.schema.sql.SqlDialect.executeBatch(SqlDialect.java:442)
    at com.google.gwtorm.jdbc.JdbcAccess.execute(JdbcAccess.java:449)
    at com.google.gwtorm.jdbc.JdbcAccess.insertAsBatch(JdbcAccess.java:212)
    at com.google.gwtorm.jdbc.JdbcAccess.insert(JdbcAccess.java:165)
    ... 15 more
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_E ON PUBLIC.ACCOUNT_SSH_KEYS(ACCOUNT_ID, SEQ) VALUES ( /_ key:4 */ null, null, 1000000, 0)"; SQL statement:
INSERT INTO account_ssh_keys(ssh_public_key,valid,account_id,seq)VALUES(?,?,?,?) [23505-174]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
    at org.h2.message.DbException.get(DbException.java:172)
    at org.h2.message.DbException.get(DbException.java:149)
    at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:101)
    at org.h2.index.PageBtree.find(PageBtree.java:121)

```
```

**Comment by davsclaus** [comment]
Have you got this to work? 

There has been a lot of changes and others like @jstrachan and @rawlingsj and @cmoulliard are working on the CI/CD stuff.

**Comment by cmoulliard** [comment]
This error should not be there anymore.
