### ISSUE TITLE
Kibana Liveness probe failed: dial tcp *.*.*.*:5601: connection refused 

### ISSUE THREAD

**Issue by spiner2000** [fabric8io/fabric8-installer#15]
Hello,
I have trouble with kibana pod, it's not working by defalut.  (vagrant/openshift/latest)
I see "kibana-tr1yt     Pod     unhealthy   Liveness probe failed: dial tcp 172.17.0.3:5601: connection refused (52 times in the last 24 minutes, 6 seconds) " in event log and restarts of kibana containers/
No configuration have made, just "vagrant up".

**Comment by jimmidyson** [comment]
Hi @spiner2000. Is the Elasticsearch service created & Elasticsearch pod(s) running properly?

**Comment by spiner2000** [comment]
Hi @jimmidyson elsticsearch looks fine.

**Comment by jimmidyson** [comment]
Could you try to get the logs of the kibana pod with oc logs?

**Comment by spiner2000** [comment]
++ curl -s -f -o /dev/null --connect-timeout 1 -m 1 --head http://172.30.142.85:9200
- sleep 0.1
  ++ curl -s -f -o /dev/null --connect-timeout 1 -m 1 --head http://172.30.142.85:9200
- sleep 0.1
  ++ curl -s -f -o /dev/null --connect-timeout 1 -m 1 --head http://172.30.142.85:9200
- sleep 0.1
  ++ curl -s -f -o /dev/null --connect-timeout 1 -m 1 --head http://172.30.142.85:9200
  ++ curl -s -f -o /dev/null http://172.30.142.85:9200/.kibana
- '[' ']'
- curl -s -f -XPUT -d@/index-pattern.json 'http://172.30.142.85:9200/.kibana/index-pattern/\[logstash-\]YYYY.MM.DD'
- curl -s -f -XPUT -d@/fabric8-search.json http://172.30.142.85:9200/.kibana/search/Fabric8
- curl -s -f -XPUT -d@/fabric8-dashboard.json http://172.30.142.85:9200/.kibana/dashboard/Fabric8
- curl -s -f -XPUT -d@/kibana-config.json http://172.30.142.85:9200/.kibana/config/4.1.0
- sleep infinity

last lines of log in kibana-config container
log in kibana container is empty

**Comment by jimmidyson** [comment]
There are 2 containers in the kibana pod, those are the logs for the configuration container where we initialise some simple log dashboards.

Could you try to grab the other container logs with "oc logs <POD_ID> kibana" (I think it's that anyway!).

**Comment by spiner2000** [comment]
@jimmidyson updated previous comment "log of kibana container is empty" :)

**Comment by spiner2000** [comment]
@jimmidyson  But i see this in elsticsearch container.
[DEBUG][action.search.type       ] [Brainchild] [.kibana][0], node[RwDB46q9QoKhk7X9IzFYSQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@42b9e0ef] lastShard [true]
org.elasticsearch.search.SearchParseException: [.kibana][0]: from[-1],size[1000]: Parse Failure [Failed to parse source [{"size":1000,"sort":[{"buildNum":{"order":"desc"}}],"query":{"filtered":{"filter":{"bool":{"must_not":[{"query":{"match":{"_id":"@@version"}}}]}}}}}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.search.SearchParseException: [.kibana][0]: from[-1],size[1000]: Parse Failure [No mapping found for [buildNum] in order to sort on]
        at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:214)
        at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:188)
        at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:86)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)
        ... 9 more

**Comment by jimmidyson** [comment]
OK thanks - I'll take a look.

**Comment by spiner2000** [comment]
By the way, i have the same issue with native openshift origin installation and "logging" template.

**Comment by jimmidyson** [comment]
Do you mean the one from the OpenShift docs or from fabric8? They're pretty much the same IIRC so likely to have same (bad) behaviour.

**Comment by spiner2000** [comment]
Yes it's based on fabric8 guide.

**Comment by jimmidyson** [comment]
This seems to be working now. Please reopen if there are any issues still.
