### ISSUE TITLE
Cannot access internet from fabric8 containers

### ISSUE THREAD

**Issue by nicolaferraro** [fabric8io/fabric8-installer#88]
Hi, I'm trying to setup the environment to be able to contribute actively to fabric8 but I've some issues with the internet connection: containers are not able to connect to the internet.

I setup the environment using the latest installer (actually I also tried old versions of the installer, with the same result).
Environment:
- Fedora 23
- Vagrant on Virtualbox
- Vagrantfile in path /vagrant/openshift/Vagrantfile

When I `vagrant up --provider virtualbox` I see the following warnings:

```
==> default: Importing secret: jenkins-ssh-config/config
==> default: Warning: open jenkins-ssh-config/config: no such file or directory
==> default: 
==> default: jenkins-ssh-config secret.....................................................✘ secrets "jenkins-ssh-config" already exists
==> default: Importing secret: jenkins-release-gpg/gpg.conf
==> default: Warning: open jenkins-release-gpg/gpg.conf: no such file or directory
==> default: Importing secret: jenkins-release-gpg/secring.gpg
==> default: Warning: open jenkins-release-gpg/secring.gpg: no such file or directory
==> default: Importing secret: jenkins-release-gpg/pubring.gpg
==> default: Warning: open jenkins-release-gpg/pubring.gpg: no such file or directory
==> default: Importing secret: jenkins-release-gpg/trustdb.gpg
==> default: Warning: open jenkins-release-gpg/trustdb.gpg: no such file or directory
==> default: 
==> default: jenkins-release-gpg secret....................................................✘ secrets "jenkins-release-gpg" already exists
==> default: Importing secret: jenkins-maven-settings/settings.xml
==> default: Warning: open jenkins-maven-settings/settings.xml: no such file or directory
==> default: Importing secret: Using deafult maven settings from https://raw.githubusercontent.com/fabric8io/gofabric8/master/default-secrets/mvnsettings.xml
==> default: jenkins-maven-settings secret.................................................✘ secrets "jenkins-maven-settings" already exists
==> default: Importing secret: jenkins-hub-api-token/hub
==> default: Warning: open jenkins-hub-api-token/hub: no such file or directory
==> default: 
==> default: jenkins-hub-api-token secret..................................................✘ secrets "jenkins-hub-api-token" already exists
==> default: Importing secret: jenkins-docker-cfg/config.json
==> default: Warning: open jenkins-docker-cfg/config.json: no such file or directory
==> default: 
==> default: jenkins-docker-cfg secret.....................................................✘ secrets "jenkins-docker-cfg" already exists
==> default: Importing secret: jenkins-git-ssh/ssh-key
==> default: Importing secret: jenkins-git-ssh/ssh-key.pub
==> default: No secrets found on local filesystem, generating SSH public and private key pair
==> default: jenkins-git-ssh secret........................................................✘ secrets "jenkins-git-ssh" already exists
==> default: Importing secret: jenkins-master-ssh/ssh-key
==> default: Importing secret: jenkins-master-ssh/ssh-key.pub
==> default: No secrets found on local filesystem, generating SSH public and private key pair
==> default: jenkins-master-ssh secret.....................................................✘ secrets "jenkins-master-ssh" already exists
```

After the machine has started, I tried to deploy the CD pipeline and I got a **yellow X** on the following secrets:
- jenkins-docker-cfg
- jenkins-git-ssh
- jenkins-hub-api-token
- jenkins-master-ssh
- jenkins-release-gpg
- jenkins-ssh-config

The explanation of the issue is more or less the same for all secrets. It is like:

```
kind: Status
apiVersion: v1
metadata: {}
status: Failure
message: >-
  Secret "jenkins-docker-cfg" is invalid: type: Invalid value:
  "fabric8.io/jenkins-docker-cfg": field is immutable
reason: Invalid
details:
  name: jenkins-docker-cfg
  kind: Secret
  causes:
    - reason: FieldValueInvalid
      message: 'Invalid value: "fabric8.io/jenkins-docker-cfg": field is immutable'
      field: type
code: 422
```

The secrets are present in the runtime config, so I assume that it is just a warning, but I reported it for the sake of completeness.

The **real problem** happens when I try to create the first application. I create a new app using the UI, choose the "integration" project type (or anything else), specify a name and then I get a:

**HTTP ERROR 500**
**Problem accessing /api/forge/command/execute/project-new.**
**Reason: Server Error**

Stacktrace:

```
org.jboss.forge.furnace.manager.maven.MavenOperationException: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to transfer io.fabric8.archetypes:java-camel-spring-archetype:jar:2.2.114 from http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact io.fabric8.archetypes:java-camel-spring-archetype:jar:2.2.114 from/to central (http://repo1.maven.org/maven2): Error transferring file: Connection refused
    at org.jboss.forge.addon.maven.dependencies.MavenDependencyResolver.resolveArtifact(MavenDependencyResolver.java:208)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
    at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
    at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
    at org.jboss.forge.addon.maven.dependencies.MavenDependencyResolver_$$_javassist_3836640f-2376-4c8b-8e59-a2d9a3c39da3.resolveArtifact(MavenDependencyResolver_$$_javassist_3836640f-2376-4c8b-8e59-a2d9a3c39da3.java)
    at org.jboss.forge.addon.maven.projects.archetype.ui.AbstractArchetypeSelectionWizardStep.execute(AbstractArchetypeSelectionWizardStep.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
    at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
    at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
    at io.fabric8.forge.camel.commands.project.projecttypes.CamelProjectArchetypeStep_$$_javassist_a41d3733-f3a2-4eab-a678-2a9313369e85.execute(CamelProjectArchetypeStep_$$_javassist_a41d3733-f3a2-4eab-a678-2a9313369e85.java)
    at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:162)
    at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:152)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
    at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
    at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
    at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_114149de-174e-41d8-8d1a-2d077258d1a1.execute(CommandController_$$_javassist_114149de-174e-41d8-8d1a-2d077258d1a1.java)
    at io.fabric8.forge.rest.CommandsResource.doExecute(CommandsResource.java:333)
    at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:277)
    at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:273)
    at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:598)
    at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:559)
    at io.fabric8.forge.rest.CommandsResource.executeCommand(CommandsResource.java:273)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
    at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
    at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:816)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle(Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to transfer io.fabric8.archetypes:java-camel-spring-archetype:jar:2.2.114 from http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact io.fabric8.archetypes:java-camel-spring-archetype:jar:2.2.114 from/to central (http://repo1.maven.org/maven2): Error transferring file: Connection refused
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
    at org.jboss.forge.addon.maven.dependencies.MavenDependencyResolver.resolveArtifact(MavenDependencyResolver.java:192)
    ... 78 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Failure to transfer io.fabric8.archetypes:java-camel-spring-archetype:jar:2.2.114 from http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact io.fabric8.archetypes:java-camel-spring-archetype:jar:2.2.114 from/to central (http://repo1.maven.org/maven2): Error transferring file: Connection refused
    at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:238)
    at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
    ... 82 more
```

It seemed that the container was not able to connect to the internet, so I tried to investigate:

```
[vagrant@vagrant ~]$ oc exec -it fabric8-forge-k4rxk bash
[root@fabric8-forge-k4rxk /]# curl -L http://repo1.maven.org/maven2
curl: (7) Failed connect to repo1.maven.org:80; Connection refused
[root@fabric8-forge-k4rxk /]#
```

Looking at other containers:

```
[vagrant@vagrant ~]$ oc exec -it fabric8-puewo bash
bash-4.2$ curl -L http://repo1.maven.org/maven2
curl: (7) Failed connect to repo1.maven.org:80; Connection refused
bash-4.2$
```

I cannot even install any other other software to investigate (dig, telnet) as there is no connection.

Do you have any clue about what is causing the issue?

Thanks,
Nicola

**Comment by rawlingsj** [comment]
What version of fabric8-forge do you have?  There should be a version `label` if you look at the replication controller..

```
oc get rc fabric8-forge
```

I had a feeling that forge was switched to use Nexus recently rather than going to maven central, that wont solve your accessing the internet problem in this case but maybe the nexus pod can access the net to get round the issue.

The latest forge release is 2.2.176

**Comment by rawlingsj** [comment]
Oh and looking forward to the contributions!!

**Comment by nicolaferraro** [comment]
Sure... I look forward for my contributions too :)

fabric8-forge is at its latest version (2.2.176) and it is using the local nexus as proxy for all maven artifacts (looked into the settings.xml).

Anyway, as you expected, nexus is not able to connect to maven central or fusesource repos...

**Comment by nicolaferraro** [comment]
I deployed a container with simple OS commands (eg. dig, nslookup and telnet) and found out that the DNS was resolving every name to 127.0.0.1. That's why I got a "connection refused".

I solved by:

```
vagrant halt
vagrant up
```

If I don't restart the VM, the DNS inside the containers does not work. After restart, new pods are able to connect.

**Comment by rawlingsj** [comment]
great news!  thanks for the update too.
